[project]
name = "joltz"
version = "0.1.0"
description = "JAX translation of Boltz-1"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boltz>=0.3.2",
    "einops>=0.8.0",
    "equinox>=0.11.10",
    "jax>=0.4.37",
    "jaxtyping>=0.2.36",
    "numpy>=1.26.3",
]
